// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqHDpfr_-n535CkP2_OTgu0rajc1498OI',
    appId: '1:589594887753:web:6aed31f7d5aad83581a198',
    messagingSenderId: '589594887753',
    projectId: 'campus-hub-app-25696',
    authDomain: 'campus-hub-app-25696.firebaseapp.com',
    storageBucket: 'campus-hub-app-25696.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz5soISmO3G_vdETG09l1yAz4XTJBcjAs',
    appId: '1:589594887753:android:1a3c000551f322d881a198',
    messagingSenderId: '589594887753',
    projectId: 'campus-hub-app-25696',
    storageBucket: 'campus-hub-app-25696.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABaq3OwB4elaQdmmXY1Iz_D97jQeK0ef4',
    appId: '1:589594887753:ios:d24ab8a8636879e581a198',
    messagingSenderId: '589594887753',
    projectId: 'campus-hub-app-25696',
    storageBucket: 'campus-hub-app-25696.firebasestorage.app',
    iosBundleId: 'com.campushub.app',
  );
}
